# 1. A Quick Example

- Bag of words : Google(20214)

- 

- Review1='Game of Thrones is about amazing tv series'
- Review2='Game of Thrones is the best tv series'
- Review3='Game of Thrones is to great'

### In the table I show all the calculations to obtain the Bag-Of-Words approach

#Vocabulary



In [1]:
Review1='Game of Thrones is about amazing tv series'
Review2='Game of Thrones is the best tv series'
Review3='Game of Thrones is to great'

In [2]:

Cols   Amazing   an   best  Game  Great  is of series so the thrones TV
R1      1         1    0      1     0     1  1   1     0  0   1       1
R2      0         0    1      1     0    
R3      0         0    0      


SyntaxError: invalid syntax (1882534402.py, line 1)

2013: Word 2 Vecotr (google)

- s1: I like apples         ======= numbers ======= vector  v1
- s2: I eat apples          ======= numbers ======= vector  v2
- s3: I don't like applies  ======= numbers ======= vector  v3

- s1 and s2     s1 and s3


- Cosine simi1(v1 and v2) === 90%
- Cosine simi2(v1 and v2) === 30%


who is VK ?

1. Vk is indian Batsman               v1
2. Messy in Hyd                       v2
3. TOday No cricket match             v3

Q V

- Cos(QV vs V1)  = answer
- Cos(QV vs V2)
- Cos(QV vs V3)


In [3]:
V=[1,2,3]

||V|| = Root over 1 sq + 2 sq + 3 Sq


SyntaxError: invalid syntax (2747544477.py, line 3)

1. what are embeddings?
   - Embeddings are numerical reprensentations of text, audio, or any data. For text (usually our focus), an embedding is:
   - - A vector( a long list of numbers)
     - Generated by a model
     - Designed so that similar meanings -> similar numbers
2. Why Do we Use Embeddings?
    - Because computers don't understand text directrly -- they understand numbers
  
    - Embeddings allow systems to:
  
    - - Search semantically ( meaning based search)
      - Build recommentation systems)
      - measures similarly between text
      - Cluster documentents
      - RAG(retrival-Argumented Generation) Including ChatGroq workflow


3. What is a Similarity Score?
   - Once you have embeddings, you meansure similarity using a mathathical formula
   - The most common one is:

 ##Cosine Similarity
   - 1.0 -> identical meaning
   - 0.0 -> unrelated
   - 1.0 -> opposite meaning
       

cos_sim=(A.B)/(||A|| .||B||)




In [4]:
!pip install sentence-transformers

In [5]:
# pip install sentences-transformers
# open anaconda prompt
# install above one
# after installations restart you kernel first


In [10]:
from sentence_transformers import SentenceTransformer
import numpy as np

In [13]:
# Open SOurce model No api - key
# For testing purpose

model = SentenceTransformer('all-MiniLM-L6-v2')

In [14]:
sentences = [
    'I like apples.',
    'I enjoy eating apples.',
    'I drive a motorcycle.'
]


In [16]:
embeddings = model.encode(sentences)


In [18]:
embeddings

array([[-0.00795677,  0.00439064,  0.00202522, ...,  0.05261281,
         0.09204265,  0.01492956],
       [ 0.04228435, -0.02286871,  0.01099177, ...,  0.04014785,
         0.01113551, -0.02590692],
       [ 0.00638028,  0.02684812,  0.01856963, ...,  0.05433159,
        -0.02654594, -0.11293572]], dtype=float32)

In [19]:
embeddings[0]

array([-7.95676839e-03,  4.39063692e-03,  2.02522310e-03,  4.47826870e-02,
       -4.11381721e-02, -1.17856078e-02,  9.93527547e-02, -1.49924280e-02,
        3.28452550e-02,  2.80843470e-02,  3.82005125e-02, -3.95743772e-02,
        3.20649669e-02, -1.52864577e-02,  3.38637978e-02,  7.11705955e-03,
        6.39917478e-02, -4.05895263e-02, -4.73222211e-02, -1.12335673e-02,
       -7.96146765e-02,  7.19404817e-02,  5.19621931e-02, -1.93749424e-02,
        9.35441523e-04,  4.32008915e-02,  1.97204258e-02, -3.00486647e-02,
       -8.23600590e-02, -3.70823182e-02, -5.02394661e-02,  1.10583445e-02,
        2.05313228e-02,  1.45487413e-02, -3.76089290e-02,  1.48732793e-02,
        1.00732125e-01, -3.48994844e-02, -2.48851161e-02, -1.85872763e-02,
        1.62222772e-03,  5.87750785e-02,  5.86785786e-02,  5.20198382e-02,
       -5.73277101e-02, -1.06776608e-02,  3.00521050e-02, -4.60932925e-02,
        9.38398391e-02,  5.82441799e-02,  6.42052740e-02, -9.02684813e-04,
       -4.48686406e-02, -

In [20]:
len(embeddings[0])

384

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


In [25]:
v1=embeddings[0] #I like apples.
v2=embeddings[1] # I enjoy eating apples.
v3=embeddings[2] # I drive a motorcycle.

In [26]:
from sklearn.metrics.pairwise import cosine_similarity


In [28]:
cosine_similarity(v1, v2)


ValueError: Expected 2D array, got 1D array instead:
array=[-7.95676839e-03  4.39063692e-03  2.02522310e-03  4.47826870e-02
 -4.11381721e-02 -1.17856078e-02  9.93527547e-02 -1.49924280e-02
  3.28452550e-02  2.80843470e-02  3.82005125e-02 -3.95743772e-02
  3.20649669e-02 -1.52864577e-02  3.38637978e-02  7.11705955e-03
  6.39917478e-02 -4.05895263e-02 -4.73222211e-02 -1.12335673e-02
 -7.96146765e-02  7.19404817e-02  5.19621931e-02 -1.93749424e-02
  9.35441523e-04  4.32008915e-02  1.97204258e-02 -3.00486647e-02
 -8.23600590e-02 -3.70823182e-02 -5.02394661e-02  1.10583445e-02
  2.05313228e-02  1.45487413e-02 -3.76089290e-02  1.48732793e-02
  1.00732125e-01 -3.48994844e-02 -2.48851161e-02 -1.85872763e-02
  1.62222772e-03  5.87750785e-02  5.86785786e-02  5.20198382e-02
 -5.73277101e-02 -1.06776608e-02  3.00521050e-02 -4.60932925e-02
  9.38398391e-02  5.82441799e-02  6.42052740e-02 -9.02684813e-04
 -4.48686406e-02 -4.85506319e-02  2.50208154e-02  1.63765829e-02
  3.54199745e-02  1.07522644e-02  3.66706327e-02 -8.56663100e-03
  6.44985139e-02 -6.64128363e-02 -2.16228403e-02  3.16197127e-02
  3.11859921e-02 -5.80637418e-02 -5.10279536e-02 -1.47819119e-02
 -3.92720476e-02 -3.77449114e-03  1.33345202e-02  7.08278716e-02
  8.06904063e-02  7.42032751e-02 -2.48523019e-02  2.60436404e-02
  7.40701035e-02 -5.30310832e-02 -5.34929559e-02  4.62422892e-02
 -5.98250851e-02 -3.38418335e-02 -3.89236435e-02  2.63308119e-02
 -1.59949008e-02 -4.06209826e-02 -2.47382093e-02  4.94539319e-03
 -7.16477484e-02  4.21851724e-02 -1.04101803e-02 -4.87391977e-03
  1.36828085e-03  4.31080014e-02  5.23645338e-03  2.03227904e-02
  4.41400781e-02 -3.37696411e-02 -5.22913486e-02  1.01654463e-01
  1.72677096e-02  2.38376055e-02 -1.06314849e-02  3.22595537e-02
  4.65896167e-02  5.80203114e-03 -1.41940370e-01 -5.22534959e-02
  4.45927493e-03  2.28152610e-02  9.62108094e-03 -3.47689949e-02
 -7.18548298e-02  6.83326414e-03  2.57429928e-02  2.87465621e-02
  4.58323248e-02  1.76816899e-02  3.06722112e-02 -2.73673180e-02
  1.64706670e-02  8.92101526e-02 -2.82264389e-02 -1.55526930e-02
 -4.48254347e-02 -2.24769413e-02  5.56438230e-02 -7.56348697e-33
 -1.06929488e-01 -9.81801189e-03  3.78628932e-02 -1.49711445e-02
  1.24509083e-02 -2.86076963e-03  3.18128206e-02  6.61913306e-02
  5.28883338e-02 -1.33967372e-02 -3.69478762e-02  4.72651944e-02
 -7.10222796e-02 -2.68192426e-03  7.54716843e-02 -5.83819002e-02
  2.85372976e-03  2.46623755e-02 -7.86184222e-02 -3.68126370e-02
 -4.86266911e-02 -2.64820624e-02 -3.42226140e-02  5.55685200e-02
 -4.91382070e-02 -1.24139421e-01  8.72573331e-02 -8.81927982e-02
  9.05497968e-02  1.55742504e-02  3.64264883e-02  3.06866318e-02
  6.59239572e-03 -6.14061132e-02 -2.82258932e-02 -1.16784675e-02
  5.40643334e-02  4.59153093e-02  1.67714246e-02  4.06574868e-02
 -4.46103960e-02  3.92371602e-02  5.82918003e-02  6.99916407e-02
  1.03775136e-01  1.87851358e-02  4.65379283e-02  4.94650900e-02
 -4.58028764e-02 -6.16227975e-03 -7.07263276e-02 -4.45879623e-02
  8.41802359e-02  8.26319903e-02 -3.51773873e-02  3.73748392e-02
  2.22036727e-02  2.87808552e-02 -7.00494647e-02  4.81744716e-03
 -9.05459374e-02  6.44337609e-02  3.06407921e-02  1.54517184e-03
 -9.71338525e-02  1.32508859e-01 -4.22875881e-02 -3.54627380e-03
 -1.34099070e-02  4.19880003e-02 -6.31242618e-02  3.45253460e-02
 -1.77878849e-02  3.91386217e-03 -1.12651803e-01 -7.82365650e-02
  3.20526175e-02 -1.90273114e-02 -2.52448004e-02 -3.86780277e-02
 -9.16660111e-03 -5.36311902e-02 -2.22031139e-02 -1.63612720e-02
  3.90280299e-02  8.69279504e-02 -6.09556288e-02 -4.13707308e-02
  6.51233047e-02 -4.47481349e-02 -1.47647653e-02  1.66484490e-02
  5.84904701e-02 -7.33032357e-03 -1.43008515e-01  6.41545217e-33
 -1.33922510e-02 -9.84059945e-02  6.61713351e-03  2.75039282e-02
 -3.32749635e-02 -6.92821667e-02 -9.52285081e-02  1.40952282e-02
 -6.00337163e-02 -7.04122242e-03 -1.54355029e-02 -1.41820274e-02
 -3.31536606e-02 -8.01028032e-03  9.50735249e-03  2.39686705e-02
  5.34251705e-03  8.10866281e-02 -1.16793280e-02  3.79531691e-03
 -1.63894203e-02  2.50132009e-02 -1.21236322e-02  1.25131281e-02
  2.86866277e-02 -2.27139220e-02 -4.51875813e-02  1.38605954e-02
 -3.07419803e-02  6.84509277e-02  4.11277451e-02 -1.42381266e-01
 -5.78316003e-02 -7.58125857e-02  5.80511801e-02  2.06637047e-02
 -8.55734423e-02 -8.30614865e-02  1.78674888e-02  3.10841817e-02
  1.08536854e-02 -9.64555144e-03  3.14371474e-02  9.71587375e-02
  4.03761901e-02  8.95847976e-02 -1.02216769e-02  8.45184103e-02
  6.04519583e-02  5.10570481e-02 -3.14106122e-02  3.95755423e-03
 -7.38928244e-02 -7.47411861e-04  1.56303495e-02 -4.71319072e-03
 -1.30688343e-02  2.21539997e-02 -4.94127795e-02 -4.16979864e-02
 -7.96580762e-02  5.75232618e-02  1.40441284e-02  1.31870387e-02
  3.30307186e-02 -2.30764262e-02 -3.96256968e-02 -8.60842541e-02
 -6.74082190e-02  1.24326730e-02  2.44818274e-02 -5.76020554e-02
 -5.18347286e-02 -4.43093330e-02 -3.57254706e-02 -2.70224083e-02
 -4.91795596e-03  4.45640571e-02 -1.06199026e-01  1.21597955e-02
  1.40722664e-02  1.07208408e-01 -2.86923498e-02  8.81066695e-02
  8.93273279e-02  4.89729904e-02  5.81684895e-03 -4.94560041e-03
 -4.82989438e-02  6.75800666e-02  2.41291691e-02  7.63501087e-03
  6.68933894e-03 -3.45129594e-02 -2.78325286e-02 -1.58267515e-08
 -5.26154377e-02 -1.62748750e-02  8.91040266e-02 -4.08070744e-04
  1.53743234e-02  8.70466083e-02 -1.26184523e-01  4.50120345e-02
  1.34735135e-02 -6.01930581e-02  5.19592762e-02  8.49388689e-02
 -1.26265869e-01  7.14801773e-02  7.09426776e-02  7.53841177e-03
  5.72820455e-02 -2.28887163e-02  2.44910247e-03  6.99302331e-02
 -9.41895023e-02  4.77777645e-02 -4.07440402e-03  5.45495600e-02
 -1.40673276e-02  4.55940589e-02 -6.40083198e-03 -2.30109207e-02
  6.50961697e-02  1.06723815e-01  4.21458483e-02  4.29827571e-02
 -8.22935700e-02  6.58483133e-02 -8.98222439e-03 -5.28123751e-02
 -1.63855571e-02  6.00280426e-03 -1.75126661e-02 -6.36531934e-02
 -5.38827442e-02  5.08342590e-03 -1.37616023e-02 -8.54133144e-02
 -7.07073808e-02 -1.38765527e-02  5.80859110e-02 -2.15916596e-02
 -3.56485718e-03  8.85962695e-02  4.79116514e-02  1.54987164e-02
  9.47962776e-02  8.30872878e-02  5.33134677e-02 -2.12073810e-02
  2.45794710e-02 -7.76007399e-02  1.45957163e-02  7.17519149e-02
  9.50413048e-02  5.26128076e-02  9.20426548e-02  1.49295591e-02].
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.

In [29]:
v1=embeddings[0].reshape(-1, 1) #I like apples.
v2=embeddings[1].reshape(-1, 1) # I enjoy eating apples.
v3=embeddings[2].reshape(-1, 1) # I drive a motorcycle.

In [30]:
#v1

In [33]:
from sklearn.metrics.pairwise import cosine_similarity


In [34]:
cosine_similarity(v1, v2)

array([[-1.,  1., -1., ..., -1., -1.,  1.],
       [ 1., -1.,  1., ...,  1.,  1., -1.],
       [ 1., -1.,  1., ...,  1.,  1., -1.],
       ...,
       [ 1., -1.,  1., ...,  1.,  1., -1.],
       [ 1., -1.,  1., ...,  1.,  1., -1.],
       [ 1., -1.,  1., ...,  1.,  1., -1.]], dtype=float32)

In [35]:
def cosine_sim(a, b):
    return np.dot(a, b)/(np.linalg.norm(a) * np.linalg.norm(b))

In [37]:
v1=embeddings[0] #I like apples.
v2=embeddings[1] # I enjoy eating apples.
v3=embeddings[2] # I drive a motorcycle.

cosine_sim(v1, v2)

0.83743393

In [38]:
Nr=np.dot(v1, v2)
norm_v1=np.linalg.norm(v1)
norm_v2=np.linalg.norm(v2)
Dr=norm_v1*norm_v2
cosine_sim(v1, v2), Nr/Dr

(0.83743393, 0.83743393)